-- MARILAB MOVER E1.6.9 - PUSH RELIABILITY MULTI-DISPOSITIVO
-- Autore ufficiale: Fabio Carratù
-- Applicare una sola volta dopo le migrazioni precedenti.
-- Introduce una coda per singolo dispositivo, claim atomico, retry e ricevute Expo.

begin;

alter table public.app_notifications
  add column if not exists push_status text not null default 'pending',
  add column if not exists push_completed_at timestamptz,
  add column if not exists push_last_attempt_at timestamptz,
  add column if not exists push_attempts integer not null default 0;

update public.app_notifications
set push_status = case when push_sent_at is not null then 'completed' else 'pending' end,
    push_completed_at = case when push_sent_at is not null then coalesce(push_completed_at, push_sent_at) else push_completed_at end
where push_status is null
   or (push_sent_at is not null and push_status = 'pending');

-- Non reinviare lo storico precedente alla release: resta consultabile nell'app,
-- ma viene chiuso come dispatch scaduto per non bloccare la coda recente.
update public.app_notifications
set push_status = 'failed',
    push_completed_at = coalesce(push_completed_at, now())
where push_sent_at is null
  and created_at < now() - interval '24 hours'
  and push_status = 'pending';

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'app_notifications_push_status_check'
      and conrelid = 'public.app_notifications'::regclass
  ) then
    alter table public.app_notifications
      add constraint app_notifications_push_status_check
      check (push_status in ('pending', 'queued', 'processing', 'waiting_receipts', 'retrying', 'completed', 'partial', 'failed', 'no_targets'));
  end if;
end;
$$;

create table if not exists public.push_deliveries (
  id bigint generated by default as identity primary key,
  notification_id bigint not null references public.app_notifications(id) on delete cascade,
  provider text not null check (provider in ('expo', 'web')),
  target_id bigint not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'processing', 'accepted', 'sent', 'retry', 'invalid', 'failed', 'cancelled')),
  attempts integer not null default 0 check (attempts >= 0),
  next_attempt_at timestamptz not null default now(),
  lease_until timestamptz,
  ticket_id text,
  accepted_at timestamptz,
  sent_at timestamptz,
  last_status_code integer,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (notification_id, provider, target_id)
);

create index if not exists push_deliveries_claim_idx
  on public.push_deliveries(status, next_attempt_at, notification_id);
create index if not exists push_deliveries_receipt_idx
  on public.push_deliveries(provider, status, accepted_at)
  where provider = 'expo' and status = 'accepted';
create index if not exists push_deliveries_notification_idx
  on public.push_deliveries(notification_id, status);
create index if not exists push_deliveries_user_idx
  on public.push_deliveries(user_id, created_at desc);

drop trigger if exists push_deliveries_updated_at on public.push_deliveries;
create trigger push_deliveries_updated_at
  before update on public.push_deliveries
  for each row execute function public.set_updated_at();

alter table public.push_deliveries enable row level security;
revoke all on public.push_deliveries from public, anon, authenticated;
grant select, insert, update, delete on public.push_deliveries to service_role;
grant usage, select on sequence public.push_deliveries_id_seq to service_role;

create or replace function public.claim_push_deliveries(
  p_notification_id bigint default null,
  p_limit integer default 500
)
returns table (
  delivery_id bigint,
  notification_id bigint,
  provider text,
  target_id bigint,
  user_id uuid,
  attempts integer,
  title text,
  body text,
  request_id uuid,
  kind text,
  expo_push_token text,
  endpoint text,
  p256dh text,
  auth text
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  return query
  with picked as (
    select d.id
    from public.push_deliveries d
    where (p_notification_id is null or d.notification_id = p_notification_id)
      and d.attempts < 6
      and (
        (d.status in ('pending', 'retry') and d.next_attempt_at <= now())
        or (d.status = 'processing' and coalesce(d.lease_until, '-infinity'::timestamptz) <= now())
      )
    order by d.next_attempt_at, d.id
    for update skip locked
    limit greatest(1, least(coalesce(p_limit, 500), 1000))
  ), claimed as (
    update public.push_deliveries d
    set status = 'processing',
        attempts = d.attempts + 1,
        lease_until = now() + interval '3 minutes',
        last_error = null,
        last_status_code = null
    from picked p
    where d.id = p.id
    returning d.*
  )
  select
    c.id,
    c.notification_id,
    c.provider,
    c.target_id,
    c.user_id,
    c.attempts,
    n.title,
    n.body,
    n.request_id,
    n.kind::text,
    t.expo_push_token,
    w.endpoint,
    w.p256dh,
    w.auth
  from claimed c
  join public.app_notifications n on n.id = c.notification_id
  left join public.push_tokens t
    on c.provider = 'expo' and t.id = c.target_id and t.active = true
  left join public.web_push_subscriptions w
    on c.provider = 'web' and w.id = c.target_id and w.active = true;
end;
$$;

create or replace function public.finalize_push_notification(p_notification_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  total_count integer := 0;
  sent_count integer := 0;
  accepted_count integer := 0;
  pending_count integer := 0;
  failed_count integer := 0;
  invalid_count integer := 0;
  max_attempts integer := 0;
  final_status text;
begin
  select
    count(*)::integer,
    count(*) filter (where status = 'sent')::integer,
    count(*) filter (where status = 'accepted')::integer,
    count(*) filter (where status in ('pending', 'processing', 'retry', 'accepted'))::integer,
    count(*) filter (where status = 'failed')::integer,
    count(*) filter (where status in ('invalid', 'cancelled'))::integer,
    coalesce(max(attempts), 0)::integer
  into total_count, sent_count, accepted_count, pending_count, failed_count, invalid_count, max_attempts
  from public.push_deliveries
  where notification_id = p_notification_id;

  if total_count = 0 then
    final_status := 'no_targets';
    update public.app_notifications
    set push_status = final_status,
        push_completed_at = now(),
        push_last_attempt_at = now(),
        push_attempts = greatest(push_attempts, max_attempts)
    where id = p_notification_id;
  elsif pending_count > 0 then
    final_status := case
      when accepted_count > 0 then 'waiting_receipts'
      when sent_count > 0 then 'processing'
      when exists (
        select 1 from public.push_deliveries
        where notification_id = p_notification_id and status = 'retry'
      ) then 'retrying'
      else 'processing'
    end;
    update public.app_notifications
    set push_status = final_status,
        push_completed_at = null,
        push_last_attempt_at = now(),
        push_attempts = greatest(push_attempts, max_attempts)
    where id = p_notification_id;
  else
    final_status := case
      when sent_count = total_count then 'completed'
      when sent_count > 0 then 'partial'
      else 'failed'
    end;
    update public.app_notifications
    set push_status = final_status,
        push_completed_at = now(),
        push_sent_at = case when sent_count > 0 then coalesce(push_sent_at, now()) else push_sent_at end,
        push_last_attempt_at = now(),
        push_attempts = greatest(push_attempts, max_attempts)
    where id = p_notification_id;
  end if;

  return jsonb_build_object(
    'notificationId', p_notification_id,
    'status', final_status,
    'total', total_count,
    'sent', sent_count,
    'accepted', accepted_count,
    'pending', pending_count,
    'failed', failed_count,
    'invalid', invalid_count,
    'attempts', max_attempts
  );
end;
$$;

revoke all on function public.claim_push_deliveries(bigint, integer) from public, anon, authenticated;
revoke all on function public.finalize_push_notification(bigint) from public, anon, authenticated;
grant execute on function public.claim_push_deliveries(bigint, integer) to service_role;
grant execute on function public.finalize_push_notification(bigint) to service_role;

create or replace function public.admin_push_diagnostics()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare result jsonb;
begin
  if not public.is_admin() then raise exception 'Funzione riservata agli Admin'; end if;

  select jsonb_build_object(
    'active_users', (select count(*) from public.profiles p where p.active = true),
    'native_tokens', (select count(*) from public.push_tokens t where t.active = true),
    'web_subscriptions', (select count(*) from public.web_push_subscriptions w where w.active = true),
    'active_tokens',
      (select count(*) from public.push_tokens t where t.active = true) +
      (select count(*) from public.web_push_subscriptions w where w.active = true),
    'pending_deliveries', (select count(*) from public.push_deliveries d where d.status in ('pending', 'processing', 'retry', 'accepted')),
    'failed_deliveries_24h', (select count(*) from public.push_deliveries d where d.status in ('failed', 'invalid') and d.updated_at >= now() - interval '24 hours'),
    'users_without_token', coalesce((
      select jsonb_agg(jsonb_build_object('id', p.id, 'full_name', p.full_name, 'email', p.email) order by p.full_name)
      from public.profiles p
      where p.active = true
        and not exists (select 1 from public.push_tokens t where t.user_id = p.id and t.active = true)
        and not exists (select 1 from public.web_push_subscriptions w where w.user_id = p.id and w.active = true)
    ), '[]'::jsonb)
  ) into result;

  return result;
end;
$$;

revoke all on function public.admin_push_diagnostics() from public, anon;
grant execute on function public.admin_push_diagnostics() to authenticated;

-- Hardening: la notifica può essere creata soltanto come conseguenza di un'azione
-- realmente eseguita dall'utente. Impedisce broadcast arbitrari tramite chiamate RPC manuali.
create or replace function public.create_app_notification(
  p_kind text,
  p_title text,
  p_body text,
  p_request_id uuid default null,
  p_recipient_user_id uuid default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  notification_id bigint;
  caller_is_admin boolean := public.is_admin();
begin
  if not public.is_active_user() then
    raise exception 'Account non autorizzato';
  end if;

  if p_kind not in ('request', 'status', 'assignment', 'reminder', 'chat', 'system') then
    raise exception 'Tipo notifica non valido';
  end if;

  if length(btrim(coalesce(p_title, ''))) not between 1 and 160
     or length(btrim(coalesce(p_body, ''))) not between 1 and 1000 then
    raise exception 'Contenuto notifica non valido';
  end if;

  if p_recipient_user_id is not null and not exists (
    select 1 from public.profiles p
    where p.id = p_recipient_user_id and p.active = true
  ) then
    raise exception 'Destinatario non disponibile';
  end if;

  if (
    select count(*)
    from public.app_notifications n
    where n.created_by = auth.uid()
      and n.created_at >= now() - interval '10 minutes'
  ) >= 60 then
    raise exception 'Troppe notifiche create: riprova tra qualche minuto';
  end if;

  if p_kind = 'system' then
    if not caller_is_admin and (p_recipient_user_id is distinct from auth.uid() or p_request_id is not null) then
      raise exception 'Le notifiche di sistema globali sono riservate agli Admin';
    end if;
  elsif p_kind = 'reminder' then
    if not caller_is_admin then
      raise exception 'I promemoria possono essere generati soltanto dal sistema';
    end if;
  elsif p_kind = 'request' then
    if p_request_id is null or p_recipient_user_id is not null or not exists (
      select 1
      from public.delivery_requests r
      where r.id = p_request_id
        and r.requester_id = auth.uid()
        and r.created_at >= now() - interval '10 minutes'
    ) then
      raise exception 'La notifica non corrisponde a una richiesta appena creata';
    end if;
  elsif p_kind in ('status', 'assignment') then
    if p_request_id is null or p_recipient_user_id is not null or not exists (
      select 1
      from public.request_events e
      where e.request_id = p_request_id
        and e.actor_id = auth.uid()
        and e.created_at >= now() - interval '10 minutes'
        and e.event_type in ('status_changed', 'mover_assigned')
    ) then
      raise exception 'La notifica non corrisponde a un aggiornamento recente della consegna';
    end if;
  elsif p_kind = 'chat' then
    if not exists (
      select 1
      from public.chat_messages m
      where m.sender_id = auth.uid()
        and m.created_at >= now() - interval '10 minutes'
        and m.request_id is not distinct from p_request_id
        and m.recipient_id is not distinct from p_recipient_user_id
        and m.deleted_at is null
    ) then
      raise exception 'La notifica non corrisponde a un messaggio appena inviato';
    end if;
  end if;

  insert into public.app_notifications(
    kind, title, body, request_id, created_by, recipient_user_id
  ) values (
    p_kind, btrim(p_title), btrim(p_body), p_request_id, auth.uid(), p_recipient_user_id
  ) returning id into notification_id;

  return notification_id;
end;
$$;

revoke all on function public.create_app_notification(text, text, text, uuid, uuid) from public, anon;
grant execute on function public.create_app_notification(text, text, text, uuid, uuid) to authenticated;

commit;

notify pgrst, 'reload schema';
