-- Marilab Mover E1.6.0 Fase 3
-- Web Push per Chrome/Edge/Safari macOS e web app iPhone/iPad aggiunta alla Home.

begin;

create table if not exists public.web_push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists web_push_subscriptions_user_idx
  on public.web_push_subscriptions(user_id, active);

alter table public.web_push_subscriptions enable row level security;

drop policy if exists web_push_own_select on public.web_push_subscriptions;
create policy web_push_own_select on public.web_push_subscriptions
  for select to authenticated
  using (user_id = auth.uid() and public.is_active_user());

drop policy if exists web_push_own_insert on public.web_push_subscriptions;
create policy web_push_own_insert on public.web_push_subscriptions
  for insert to authenticated
  with check (user_id = auth.uid() and public.is_active_user());

drop policy if exists web_push_own_update on public.web_push_subscriptions;
create policy web_push_own_update on public.web_push_subscriptions
  for update to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

drop policy if exists web_push_own_delete on public.web_push_subscriptions;
create policy web_push_own_delete on public.web_push_subscriptions
  for delete to authenticated
  using (user_id = auth.uid());

drop trigger if exists web_push_subscriptions_updated_at on public.web_push_subscriptions;
create trigger web_push_subscriptions_updated_at
  before update on public.web_push_subscriptions
  for each row execute function public.set_updated_at();

revoke all on public.web_push_subscriptions from anon, public;
grant select, insert, update, delete on public.web_push_subscriptions to authenticated;
grant usage, select on sequence public.web_push_subscriptions_id_seq to authenticated;

create or replace function public.admin_push_diagnostics()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare result jsonb;
begin
  if not public.is_admin() then raise exception 'Funzione riservata agli Admin'; end if;

  select jsonb_build_object(
    'active_users', (select count(*) from public.profiles p where p.active = true),
    'native_tokens', (select count(*) from public.push_tokens t where t.active = true),
    'web_subscriptions', (select count(*) from public.web_push_subscriptions w where w.active = true),
    'active_tokens',
      (select count(*) from public.push_tokens t where t.active = true) +
      (select count(*) from public.web_push_subscriptions w where w.active = true),
    'users_without_token', coalesce((
      select jsonb_agg(jsonb_build_object('id', p.id, 'full_name', p.full_name, 'email', p.email) order by p.full_name)
      from public.profiles p
      where p.active = true
        and not exists (
          select 1 from public.push_tokens t
          where t.user_id = p.id and t.active = true
        )
        and not exists (
          select 1 from public.web_push_subscriptions w
          where w.user_id = p.id and w.active = true
        )
    ), '[]'::jsonb)
  ) into result;

  return result;
end;
$$;

revoke all on function public.admin_push_diagnostics() from public, anon;
grant execute on function public.admin_push_diagnostics() to authenticated;

commit;
