-- MARILAB MOVER E0.4 - SCHEMA REALE SUPABASE
-- Autore: Fabio Carratù
-- Progetto completamente separato da FMED.
-- Eseguire una sola volta nel SQL Editor del nuovo progetto Supabase.
-- Non inserire dati sanitari, nomi di pazienti o allegati.

create extension if not exists pgcrypto;

create type public.user_role as enum ('requester', 'mover', 'admin');
create type public.request_priority as enum ('normal', 'urgent');
create type public.request_status as enum (
  'pending', 'approved', 'assigned', 'picked_up', 'in_transit',
  'delivered', 'return_required', 'completed', 'cancelled'
);

create sequence public.request_code_seq start 1001;

create table public.sites (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  short_name text not null,
  address text not null,
  maps_query text,
  contact_name text,
  contact_phone text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text not null,
  role public.user_role not null default 'requester',
  site_id uuid references public.sites(id) on delete set null,
  phone text,
  active boolean not null default true,
  must_change_password boolean not null default true,
  last_access_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_email_lowercase check (email = lower(email))
);
create unique index profiles_email_unique_idx on public.profiles (lower(email));

create table public.equipment (
  id uuid primary key default gen_random_uuid(),
  inventory_code text not null unique,
  name text not null,
  brand text,
  model text,
  serial_number text,
  home_site_id uuid not null references public.sites(id),
  current_site_id uuid not null references public.sites(id),
  movable boolean not null default true,
  active boolean not null default true,
  accessories text[] not null default '{}',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.delivery_requests (
  id uuid primary key default gen_random_uuid(),
  code text not null unique default ('MM-' || nextval('public.request_code_seq')::text),
  equipment_id uuid not null references public.equipment(id),
  requester_id uuid not null references public.profiles(id),
  pickup_site_id uuid not null references public.sites(id),
  destination_site_id uuid not null references public.sites(id),
  assigned_mover_id uuid references public.profiles(id),
  assigned_mover_ids uuid[] not null default '{}',
  requested_date date not null,
  requested_time time not null,
  return_date date,
  return_time time,
  priority public.request_priority not null default 'normal',
  status public.request_status not null default 'pending',
  note text,
  cancelled_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint different_sites check (pickup_site_id <> destination_site_id),
  constraint return_time_requires_date check (return_time is null or return_date is not null),
  constraint note_length check (note is not null and length(btrim(note)) between 3 and 1500)
);

create table public.request_events (
  id bigint generated by default as identity primary key,
  request_id uuid not null references public.delivery_requests(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  event_type text not null,
  previous_status public.request_status,
  new_status public.request_status,
  note text,
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now()
);

create table public.push_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  expo_push_token text not null unique,
  platform text not null check (platform in ('android', 'ios', 'web')),
  device_name text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.app_notifications (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('request', 'status', 'assignment', 'reminder', 'chat', 'system')),
  title text not null check (length(title) between 1 and 160),
  body text not null check (length(body) between 1 and 1000),
  request_id uuid references public.delivery_requests(id) on delete cascade,
  created_by uuid references public.profiles(id) on delete set null,
  push_sent_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.notification_reads (
  notification_id bigint not null references public.app_notifications(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  read_at timestamptz not null default now(),
  primary key (notification_id, user_id)
);

-- Registro tecnico per evitare promemoria duplicati. Non contiene dati sanitari.
create table public.reminder_dispatches (
  id bigint generated by default as identity primary key,
  request_id uuid not null references public.delivery_requests(id) on delete cascade,
  reminder_key text not null,
  dispatched_at timestamptz not null default now(),
  unique (request_id, reminder_key)
);

-- Chat esclusivamente testuale: nessun allegato, foto, audio o file.
create table public.chat_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  request_id uuid references public.delivery_requests(id) on delete cascade,
  message text not null,
  created_at timestamptz not null default now(),
  constraint chat_message_not_blank check (length(btrim(message)) between 1 and 1000)
);

create index delivery_requests_date_idx on public.delivery_requests(requested_date, requested_time);
create index delivery_requests_status_idx on public.delivery_requests(status);
create index delivery_requests_requester_idx on public.delivery_requests(requester_id);
create index delivery_requests_mover_idx on public.delivery_requests(assigned_mover_id);
create index delivery_requests_movers_gin_idx on public.delivery_requests using gin (assigned_mover_ids);
create index delivery_requests_equipment_idx on public.delivery_requests(equipment_id);
create index request_events_request_idx on public.request_events(request_id, created_at desc);
create index app_notifications_created_idx on public.app_notifications(created_at desc);
create index reminder_dispatches_request_idx on public.reminder_dispatches(request_id, dispatched_at desc);
create index chat_messages_created_idx on public.chat_messages(created_at desc);
create index chat_messages_request_idx on public.chat_messages(request_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger sites_updated_at before update on public.sites for each row execute function public.set_updated_at();
create trigger profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();
create trigger equipment_updated_at before update on public.equipment for each row execute function public.set_updated_at();
create trigger delivery_requests_updated_at before update on public.delivery_requests for each row execute function public.set_updated_at();
create trigger push_tokens_updated_at before update on public.push_tokens for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id,
    lower(coalesce(new.email, new.id::text || '@local.invalid')),
    coalesce(nullif(new.raw_user_meta_data ->> 'full_name', ''), split_part(coalesce(new.email, 'utente'), '@', 1)),
    'requester'
  );
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.current_role()
returns public.user_role language sql stable security definer set search_path = '' as $$
  select role from public.profiles where id = auth.uid() and active = true;
$$;

create or replace function public.is_active_user()
returns boolean language sql stable security definer set search_path = '' as $$
  select exists(select 1 from public.profiles where id = auth.uid() and active = true);
$$;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = '' as $$
  select coalesce(public.current_role() = 'admin', false);
$$;

create or replace function public.list_user_directory()
returns table (id uuid, full_name text, email text, role public.user_role, site_id uuid, phone text, active boolean, must_change_password boolean, last_access_at timestamptz, created_at timestamptz)
language plpgsql stable security definer set search_path = '' as $$
begin
  if not public.is_active_user() then raise exception 'Accesso non autorizzato'; end if;
  return query
  select p.id, p.full_name, ''::text, p.role, p.site_id, null::text, p.active, false, null::timestamptz, p.created_at
  from public.profiles p where p.active = true order by p.full_name;
end;
$$;

create or replace function public.list_admin_users()
returns table (id uuid, full_name text, email text, role public.user_role, site_id uuid, phone text, active boolean, must_change_password boolean, last_access_at timestamptz, created_at timestamptz)
language plpgsql stable security definer set search_path = '' as $$
begin
  if not public.is_admin() then raise exception 'Funzione riservata agli Admin'; end if;
  return query
  select p.id, p.full_name, p.email, p.role, p.site_id, p.phone, p.active, p.must_change_password, p.last_access_at, p.created_at
  from public.profiles p order by p.active desc, p.full_name;
end;
$$;

create or replace function public.log_request_change()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if tg_op = 'INSERT' then
    insert into public.request_events (request_id, actor_id, event_type, new_status)
    values (new.id, auth.uid(), 'created', new.status);
  elsif old.status is distinct from new.status then
    insert into public.request_events (request_id, actor_id, event_type, previous_status, new_status)
    values (new.id, auth.uid(), 'status_changed', old.status, new.status);
  elsif old.assigned_mover_id is distinct from new.assigned_mover_id then
    insert into public.request_events (request_id, actor_id, event_type, metadata)
    values (new.id, auth.uid(), 'mover_assigned', jsonb_build_object('assigned_mover_id', new.assigned_mover_id));
  end if;
  return new;
end;
$$;

create trigger delivery_request_audit
after insert or update on public.delivery_requests for each row execute function public.log_request_change();

create or replace function public.create_delivery_request(
  p_equipment_id uuid,
  p_pickup_site_id uuid,
  p_destination_site_id uuid,
  p_requested_date date,
  p_requested_time time,
  p_return_date date default null,
  p_return_time time default null,
  p_priority public.request_priority default 'normal',
  p_note text default null
)
returns public.delivery_requests
language plpgsql security definer set search_path = '' as $$
declare created public.delivery_requests;
begin
  if not public.is_active_user() then raise exception 'Account non autorizzato'; end if;
  if p_pickup_site_id = p_destination_site_id then raise exception 'Ritiro e destinazione devono essere diversi'; end if;
  if not exists(select 1 from public.equipment e where e.id = p_equipment_id and e.active and e.movable) then raise exception 'Apparecchiatura non disponibile'; end if;
  insert into public.delivery_requests (
    equipment_id, requester_id, pickup_site_id, destination_site_id,
    requested_date, requested_time, return_date, return_time, priority, note
  ) values (
    p_equipment_id, auth.uid(), p_pickup_site_id, p_destination_site_id,
    p_requested_date, p_requested_time, p_return_date, p_return_time, p_priority, nullif(btrim(p_note), '')
  ) returning * into created;
  return created;
end;
$$;

create or replace function public.assign_delivery_mover(p_request_id uuid, p_mover_id uuid)
returns public.delivery_requests
language plpgsql security definer set search_path = '' as $$
declare updated public.delivery_requests;
begin
  if not public.is_admin() then raise exception 'Funzione riservata agli Admin'; end if;
  if not exists(select 1 from public.profiles p where p.id = p_mover_id and p.role = 'mover' and p.active) then raise exception 'Mover non valido o non attivo'; end if;
  update public.delivery_requests
  set assigned_mover_id = p_mover_id,
      status = case when status in ('pending', 'approved') then 'assigned' else status end
  where id = p_request_id and status <> 'cancelled'
  returning * into updated;
  if updated.id is null then raise exception 'Richiesta non trovata'; end if;
  return updated;
end;
$$;

create or replace function public.update_delivery_status(p_request_id uuid, p_status public.request_status)
returns public.delivery_requests
language plpgsql security definer set search_path = '' as $$
declare current_request public.delivery_requests;
declare updated public.delivery_requests;
begin
  select * into current_request from public.delivery_requests where id = p_request_id for update;
  if current_request.id is null then raise exception 'Richiesta non trovata'; end if;
  if not public.is_admin() then
    if public.current_role() <> 'mover' or current_request.assigned_mover_id is distinct from auth.uid() then
      raise exception 'Puoi aggiornare soltanto le consegne assegnate a te';
    end if;
    if not (
      (current_request.status = 'assigned' and p_status = 'picked_up') or
      (current_request.status = 'picked_up' and p_status = 'in_transit') or
      (current_request.status = 'in_transit' and p_status in ('delivered', 'completed')) or
      (current_request.status = 'delivered' and p_status in ('return_required', 'completed')) or
      (current_request.status = 'return_required' and p_status = 'completed')
    ) then raise exception 'Passaggio di stato non consentito'; end if;
  end if;

  update public.delivery_requests set status = p_status where id = p_request_id returning * into updated;

  if p_status = 'delivered' then
    update public.equipment set current_site_id = updated.destination_site_id where id = updated.equipment_id;
  elsif p_status = 'completed' then
    update public.equipment
    set current_site_id = updated.destination_site_id
    where id = updated.equipment_id;
  end if;
  return updated;
end;
$$;

create or replace function public.create_app_notification(
  p_kind text,
  p_title text,
  p_body text,
  p_request_id uuid default null
)
returns bigint language plpgsql security definer set search_path = '' as $$
declare notification_id bigint;
begin
  if not public.is_active_user() then raise exception 'Account non autorizzato'; end if;
  if p_kind not in ('request', 'status', 'assignment', 'reminder', 'chat', 'system') then raise exception 'Tipo notifica non valido'; end if;
  insert into public.app_notifications(kind, title, body, request_id, created_by)
  values (p_kind, p_title, p_body, p_request_id, auth.uid()) returning id into notification_id;
  return notification_id;
end;
$$;

create or replace function public.admin_delivery_statistics(
  p_from_date date default null,
  p_to_date date default null,
  p_site_id uuid default null,
  p_equipment_id uuid default null,
  p_mover_id uuid default null,
  p_status public.request_status default null,
  p_priority public.request_priority default null
)
returns jsonb language plpgsql stable security definer set search_path = '' as $$
declare result jsonb;
begin
  if not public.is_admin() then raise exception 'Statistiche riservate agli Admin'; end if;

  with filtered as (
    select r.*
    from public.delivery_requests r
    where (p_from_date is null or r.requested_date >= p_from_date)
      and (p_to_date is null or r.requested_date <= p_to_date)
      and (p_site_id is null or r.pickup_site_id = p_site_id or r.destination_site_id = p_site_id)
      and (p_equipment_id is null or r.equipment_id = p_equipment_id)
      and (p_mover_id is null or r.assigned_mover_id = p_mover_id)
      and (p_status is null or r.status = p_status)
      and (p_priority is null or r.priority = p_priority)
  ), completed_events as (
    select e.request_id, min(e.created_at) as completed_at
    from public.request_events e
    where e.new_status in ('delivered', 'completed')
    group by e.request_id
  )
  select jsonb_build_object(
    'total', (select count(*) from filtered),
    'completed', (select count(*) from filtered where status = 'completed'),
    'active', (select count(*) from filtered where status not in ('completed', 'cancelled')),
    'urgent', (select count(*) from filtered where priority = 'urgent'),
    'late', (select count(*) from filtered where status not in ('delivered', 'completed', 'cancelled') and (requested_date::timestamp + requested_time) < now()),
    'average_cycle_minutes', (
      select round(avg(extract(epoch from (ce.completed_at - f.created_at)) / 60.0)::numeric, 1)
      from filtered f join completed_events ce on ce.request_id = f.id
    ),
    'by_site', coalesce((
      select jsonb_agg(jsonb_build_object('id', x.id, 'label', x.label, 'count', x.count) order by x.count desc, x.label)
      from (
        select s.id::text as id, s.short_name as label, count(*)::int as count
        from filtered f join public.sites s on s.id = f.destination_site_id
        group by s.id, s.short_name
      ) x
    ), '[]'::jsonb),
    'by_equipment', coalesce((
      select jsonb_agg(jsonb_build_object('id', x.id, 'label', x.label, 'count', x.count) order by x.count desc, x.label)
      from (
        select e.id::text as id, e.name as label, count(*)::int as count
        from filtered f join public.equipment e on e.id = f.equipment_id
        group by e.id, e.name
      ) x
    ), '[]'::jsonb),
    'by_mover', coalesce((
      select jsonb_agg(jsonb_build_object('id', x.id, 'label', x.label, 'count', x.count) order by x.count desc, x.label)
      from (
        select coalesce(p.id::text, 'unassigned') as id, coalesce(p.full_name, 'Non assegnato') as label, count(*)::int as count
        from filtered f left join public.profiles p on p.id = f.assigned_mover_id
        group by p.id, p.full_name
      ) x
    ), '[]'::jsonb)
  ) into result;
  return result;
end;
$$;

-- Chiamata esclusivamente dalla funzione server pianificata.
-- Crea una sola volta i promemoria dovuti e restituisce gli ID da inviare in push.
create or replace function public.claim_due_reminders()
returns table (notification_id bigint)
language plpgsql security definer set search_path = '' as $$
begin
  return query
  with clock as (
    select timezone('Europe/Rome', now()) as local_now
  ), candidates as (
    select r.id as request_id, 'delivery_24h'::text as reminder_key,
      ('Consegna prevista domani · ' || r.code)::text as title,
      (e.name || ' da ' || pickup.short_name || ' a ' || destination.short_name || ' · ' ||
       to_char(r.requested_date, 'DD/MM/YYYY') || ' ore ' || to_char(r.requested_time, 'HH24:MI'))::text as body
    from public.delivery_requests r
    join public.equipment e on e.id = r.equipment_id
    join public.sites pickup on pickup.id = r.pickup_site_id
    join public.sites destination on destination.id = r.destination_site_id
    cross join clock c
    where r.status not in ('delivered', 'completed', 'cancelled')
      and (r.requested_date + r.requested_time) between c.local_now + interval '22 hours' and c.local_now + interval '26 hours'

    union all

    select r.id, 'delivery_2h',
      ('Consegna imminente · ' || r.code),
      (e.name || ' da ' || pickup.short_name || ' a ' || destination.short_name || ' entro le ' || to_char(r.requested_time, 'HH24:MI'))
    from public.delivery_requests r
    join public.equipment e on e.id = r.equipment_id
    join public.sites pickup on pickup.id = r.pickup_site_id
    join public.sites destination on destination.id = r.destination_site_id
    cross join clock c
    where r.status not in ('delivered', 'completed', 'cancelled')
      and (r.requested_date + r.requested_time) between c.local_now and c.local_now + interval '2 hours'

    union all

    select r.id, 'overdue',
      ('Consegna in ritardo · ' || r.code),
      (e.name || ' per ' || destination.short_name || ' risulta ancora ' || replace(r.status::text, '_', ' '))
    from public.delivery_requests r
    join public.equipment e on e.id = r.equipment_id
    join public.sites destination on destination.id = r.destination_site_id
    cross join clock c
    where r.status not in ('delivered', 'completed', 'cancelled')
      and (r.requested_date + r.requested_time) < c.local_now  ), claimed as (
    insert into public.reminder_dispatches (request_id, reminder_key)
    select distinct c.request_id, c.reminder_key from candidates c
    on conflict (request_id, reminder_key) do nothing
    returning request_id, reminder_key
  ), inserted as (
    insert into public.app_notifications (kind, title, body, request_id, created_by)
    select 'reminder', c.title, c.body, c.request_id, null
    from candidates c
    join claimed d on d.request_id = c.request_id and d.reminder_key = c.reminder_key
    returning id
  )
  select inserted.id from inserted;
end;
$$;

-- RLS: la publishable key non può leggere dati senza sessione e policy valide.
alter table public.sites enable row level security;
alter table public.profiles enable row level security;
alter table public.equipment enable row level security;
alter table public.delivery_requests enable row level security;
alter table public.request_events enable row level security;
alter table public.push_tokens enable row level security;
alter table public.app_notifications enable row level security;
alter table public.notification_reads enable row level security;
alter table public.chat_messages enable row level security;
alter table public.reminder_dispatches enable row level security;

create policy sites_read_active on public.sites for select to authenticated using (public.is_active_user());
create policy sites_admin_write on public.sites for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy profiles_read_own_or_admin on public.profiles for select to authenticated using (id = auth.uid() or public.is_admin());
create policy profiles_update_own on public.profiles for update to authenticated using (id = auth.uid() and public.is_active_user()) with check (id = auth.uid());

create policy equipment_read_active on public.equipment for select to authenticated using (public.is_active_user());
create policy equipment_admin_write on public.equipment for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy requests_read_active on public.delivery_requests for select to authenticated using (public.is_active_user());
create policy events_read_active on public.request_events for select to authenticated using (public.is_active_user());
create policy notifications_read_active on public.app_notifications for select to authenticated using (public.is_active_user());
create policy chat_read_active on public.chat_messages for select to authenticated using (public.is_active_user());
create policy chat_insert_active on public.chat_messages for insert to authenticated with check (public.is_active_user() and sender_id = auth.uid());

create policy notification_reads_own_select on public.notification_reads for select to authenticated using (user_id = auth.uid() and public.is_active_user());
create policy notification_reads_own_insert on public.notification_reads for insert to authenticated with check (user_id = auth.uid() and public.is_active_user());
create policy notification_reads_own_update on public.notification_reads for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy push_tokens_own_select on public.push_tokens for select to authenticated using (user_id = auth.uid() and public.is_active_user());
create policy push_tokens_own_insert on public.push_tokens for insert to authenticated with check (user_id = auth.uid() and public.is_active_user());
create policy push_tokens_own_update on public.push_tokens for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy push_tokens_own_delete on public.push_tokens for delete to authenticated using (user_id = auth.uid());

revoke all on public.sites, public.profiles, public.equipment, public.delivery_requests, public.request_events,
  public.push_tokens, public.app_notifications, public.notification_reads, public.chat_messages, public.reminder_dispatches from anon;

revoke all on public.sites, public.profiles, public.equipment, public.delivery_requests, public.request_events,
  public.push_tokens, public.app_notifications, public.notification_reads, public.chat_messages, public.reminder_dispatches from authenticated;

grant select, insert, update, delete on public.sites to authenticated;
grant select on public.profiles to authenticated;
grant update (must_change_password, last_access_at) on public.profiles to authenticated;
grant select, insert, update, delete on public.equipment to authenticated;
grant select on public.delivery_requests to authenticated;
grant select on public.request_events to authenticated;
grant select, insert, update, delete on public.push_tokens to authenticated;
grant select on public.app_notifications to authenticated;
grant select, insert, update on public.notification_reads to authenticated;
grant select, insert on public.chat_messages to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Le funzioni SECURITY DEFINER non sono eseguibili da utenti anonimi o dal ruolo PUBLIC.
revoke all on function public.list_user_directory() from public, anon;
revoke all on function public.list_admin_users() from public, anon;
revoke all on function public.create_delivery_request(uuid, uuid, uuid, date, time, date, time, public.request_priority, text) from public, anon;
revoke all on function public.assign_delivery_mover(uuid, uuid) from public, anon;
revoke all on function public.update_delivery_status(uuid, public.request_status) from public, anon;
revoke all on function public.create_app_notification(text, text, text, uuid) from public, anon;
revoke all on function public.admin_delivery_statistics(date, date, uuid, uuid, uuid, public.request_status, public.request_priority) from public, anon;
revoke all on function public.claim_due_reminders() from public, anon, authenticated;

grant execute on function public.list_user_directory() to authenticated;
grant execute on function public.list_admin_users() to authenticated;
grant execute on function public.create_delivery_request(uuid, uuid, uuid, date, time, date, time, public.request_priority, text) to authenticated;
grant execute on function public.assign_delivery_mover(uuid, uuid) to authenticated;
grant execute on function public.update_delivery_status(uuid, public.request_status) to authenticated;
grant execute on function public.create_app_notification(text, text, text, uuid) to authenticated;
grant execute on function public.admin_delivery_statistics(date, date, uuid, uuid, uuid, public.request_status, public.request_priority) to authenticated;
grant execute on function public.claim_due_reminders() to service_role;

-- Aggiornamenti realtime condivisi tra tutti gli utenti autenticati.
alter publication supabase_realtime add table public.delivery_requests;
alter publication supabase_realtime add table public.equipment;
alter publication supabase_realtime add table public.app_notifications;
alter publication supabase_realtime add table public.notification_reads;
alter publication supabase_realtime add table public.chat_messages;
alter publication supabase_realtime add table public.profiles;

-- MARILAB MOVER 1.1.0 - FASE 2 OPERATIVA
-- Autore ufficiale: Fabio Carratù
-- Eseguire una sola volta nel SQL Editor del progetto Supabase già configurato.
-- Flusso definitivo: Presa in carico -> Ritirata -> In viaggio -> Consegnata -> Chiusa.
-- Nessun programma rientro.

begin;

-- Compatibilità con release precedenti.
alter table public.delivery_requests
  add column if not exists assigned_mover_ids uuid[] not null default '{}';

update public.delivery_requests
set assigned_mover_ids = array[assigned_mover_id]::uuid[]
where assigned_mover_id is not null
  and coalesce(cardinality(assigned_mover_ids), 0) = 0;

-- Normalizza gli stati storici non più usati dall'app.
update public.delivery_requests
set status = 'pending'
where status = 'approved';

update public.delivery_requests
set status = 'delivered'
where status = 'return_required';

create index if not exists delivery_requests_movers_gin_idx
  on public.delivery_requests using gin (assigned_mover_ids);

-- Assegnazione Admin coerente anche con le squadre Mover.
create or replace function public.assign_delivery_mover(
  p_request_id uuid,
  p_mover_id uuid
)
returns public.delivery_requests
language plpgsql
security definer
set search_path = ''
as $$
declare
  updated public.delivery_requests;
begin
  if not public.is_admin() then
    raise exception 'Funzione riservata agli Admin';
  end if;

  if not exists (
    select 1
    from public.profiles p
    where p.id = p_mover_id
      and p.role = 'mover'
      and p.active
  ) then
    raise exception 'Mover non valido o non attivo';
  end if;

  update public.delivery_requests
  set assigned_mover_id = p_mover_id,
      assigned_mover_ids = array[p_mover_id]::uuid[],
      status = case when status in ('pending', 'approved') then 'assigned' else status end
  where id = p_request_id
    and status not in ('completed', 'cancelled')
  returning * into updated;

  if updated.id is null then
    raise exception 'Richiesta non trovata o già chiusa';
  end if;

  return updated;
end;
$$;

-- Presa in carico singola o in squadra, in un solo passaggio.
create or replace function public.take_delivery_request(
  p_request_id uuid,
  p_mover_ids uuid[]
)
returns public.delivery_requests
language plpgsql
security definer
set search_path = ''
as $$
declare
  updated public.delivery_requests;
  clean_ids uuid[];
begin
  if public.current_role() not in ('mover', 'admin') then
    raise exception 'Funzione riservata ai Mover e agli Admin';
  end if;

  select array_agg(distinct selected.mover_id)
  into clean_ids
  from unnest(coalesce(p_mover_ids, array[]::uuid[])) as selected(mover_id)
  where selected.mover_id is not null;

  if coalesce(cardinality(clean_ids), 0) = 0 then
    raise exception 'Seleziona almeno un Mover';
  end if;

  if exists (
    select 1
    from unnest(clean_ids) as selected(mover_id)
    left join public.profiles p on p.id = selected.mover_id
    where p.id is null
       or p.role <> 'mover'
       or not p.active
  ) then
    raise exception 'Uno dei Mover selezionati non è valido o non è attivo';
  end if;

  update public.delivery_requests
  set assigned_mover_ids = clean_ids,
      assigned_mover_id = clean_ids[1],
      status = case when status in ('pending', 'approved') then 'assigned' else status end
  where id = p_request_id
    and status not in ('completed', 'cancelled')
  returning * into updated;

  if updated.id is null then
    raise exception 'Richiesta non disponibile';
  end if;

  return updated;
end;
$$;

-- Transizioni rigorose della Fase 2.
create or replace function public.update_delivery_status(
  p_request_id uuid,
  p_status public.request_status
)
returns public.delivery_requests
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_request public.delivery_requests;
  updated public.delivery_requests;
  user_is_assigned boolean;
begin
  select *
  into current_request
  from public.delivery_requests
  where id = p_request_id
  for update;

  if current_request.id is null then
    raise exception 'Richiesta non trovata';
  end if;

  user_is_assigned :=
    current_request.assigned_mover_id = auth.uid()
    or auth.uid() = any(coalesce(current_request.assigned_mover_ids, array[]::uuid[]));

  if not public.is_admin() then
    if public.current_role() <> 'mover' or not user_is_assigned then
      raise exception 'Puoi aggiornare soltanto le consegne che stai gestendo';
    end if;

    if not (
      -- Compatibilità per vecchie missioni già assegnate ma rimaste pending/approved.
      (current_request.status in ('pending', 'approved', 'assigned') and p_status = 'picked_up') or
      (current_request.status = 'picked_up' and p_status = 'in_transit') or
      (current_request.status = 'in_transit' and p_status = 'delivered') or
      (current_request.status in ('delivered', 'return_required') and p_status = 'completed')
    ) then
      raise exception 'Passaggio di stato non consentito: % -> %', current_request.status, p_status;
    end if;
  end if;

  update public.delivery_requests
  set status = p_status,
      assigned_mover_id = coalesce(assigned_mover_id, auth.uid()),
      assigned_mover_ids = case
        when coalesce(cardinality(assigned_mover_ids), 0) = 0 and auth.uid() is not null
          then array[auth.uid()]::uuid[]
        else assigned_mover_ids
      end
  where id = p_request_id
  returning * into updated;

  if p_status in ('delivered', 'completed') then
    update public.equipment
    set current_site_id = updated.destination_site_id
    where id = updated.equipment_id;
  end if;

  return updated;
end;
$$;

-- Statistiche corrette per tutti i membri della squadra Mover.
create or replace function public.admin_delivery_statistics(
  p_from_date date default null,
  p_to_date date default null,
  p_site_id uuid default null,
  p_equipment_id uuid default null,
  p_mover_id uuid default null,
  p_status public.request_status default null,
  p_priority public.request_priority default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  result jsonb;
begin
  if not public.is_admin() then
    raise exception 'Statistiche riservate agli Admin';
  end if;

  with filtered as (
    select r.*
    from public.delivery_requests r
    where (p_from_date is null or r.requested_date >= p_from_date)
      and (p_to_date is null or r.requested_date <= p_to_date)
      and (p_site_id is null or r.pickup_site_id = p_site_id or r.destination_site_id = p_site_id)
      and (p_equipment_id is null or r.equipment_id = p_equipment_id)
      and (
        p_mover_id is null
        or r.assigned_mover_id = p_mover_id
        or p_mover_id = any(coalesce(r.assigned_mover_ids, array[]::uuid[]))
      )
      and (p_status is null or r.status = p_status)
      and (p_priority is null or r.priority = p_priority)
  ), completed_events as (
    select e.request_id, min(e.created_at) as completed_at
    from public.request_events e
    where e.new_status = 'completed'
    group by e.request_id
  )
  select jsonb_build_object(
    'total', (select count(*) from filtered),
    'completed', (select count(*) from filtered where status = 'completed'),
    'active', (select count(*) from filtered where status not in ('completed', 'cancelled')),
    'urgent', (select count(*) from filtered where priority = 'urgent'),
    'late', (
      select count(*)
      from filtered
      where status not in ('delivered', 'return_required', 'completed', 'cancelled')
        and (requested_date + requested_time) < timezone('Europe/Rome', now())
    ),
    'average_cycle_minutes', (
      select round(avg(extract(epoch from (ce.completed_at - f.created_at)) / 60.0)::numeric, 1)
      from filtered f
      join completed_events ce on ce.request_id = f.id
    ),
    'by_site', coalesce((
      select jsonb_agg(
        jsonb_build_object('id', x.id, 'label', x.label, 'count', x.count)
        order by x.count desc, x.label
      )
      from (
        select s.id::text as id, s.short_name as label, count(*)::int as count
        from filtered f
        join public.sites s on s.id = f.destination_site_id
        group by s.id, s.short_name
      ) x
    ), '[]'::jsonb),
    'by_equipment', coalesce((
      select jsonb_agg(
        jsonb_build_object('id', x.id, 'label', x.label, 'count', x.count)
        order by x.count desc, x.label
      )
      from (
        select e.id::text as id, e.name as label, count(*)::int as count
        from filtered f
        join public.equipment e on e.id = f.equipment_id
        group by e.id, e.name
      ) x
    ), '[]'::jsonb),
    'by_mover', coalesce((
      select jsonb_agg(
        jsonb_build_object('id', x.id, 'label', x.label, 'count', x.count)
        order by x.count desc, x.label
      )
      from (
        select
          coalesce(p.id::text, 'unassigned') as id,
          coalesce(p.full_name, 'Non assegnato') as label,
          count(*)::int as count
        from filtered f
        left join lateral unnest(
          case
            when coalesce(cardinality(f.assigned_mover_ids), 0) > 0
              then f.assigned_mover_ids
            when f.assigned_mover_id is not null
              then array[f.assigned_mover_id]::uuid[]
            else array[null::uuid]
          end
        ) as team(mover_id) on true
        left join public.profiles p on p.id = team.mover_id
        group by p.id, p.full_name
      ) x
    ), '[]'::jsonb)
  ) into result;

  return result;
end;
$$;

-- Promemoria solo per la consegna: nessun promemoria di rientro.
create or replace function public.claim_due_reminders()
returns table (notification_id bigint)
language plpgsql
security definer
set search_path = ''
as $$
begin
  return query
  with clock as (
    select timezone('Europe/Rome', now()) as local_now
  ), candidates as (
    select
      r.id as request_id,
      'delivery_24h'::text as reminder_key,
      ('Consegna prevista domani · ' || r.code)::text as title,
      (
        e.name || ' da ' || pickup.short_name || ' a ' || destination.short_name || ' · ' ||
        to_char(r.requested_date, 'DD/MM/YYYY') || ' ore ' || to_char(r.requested_time, 'HH24:MI')
      )::text as body
    from public.delivery_requests r
    join public.equipment e on e.id = r.equipment_id
    join public.sites pickup on pickup.id = r.pickup_site_id
    join public.sites destination on destination.id = r.destination_site_id
    cross join clock c
    where r.status not in ('delivered', 'return_required', 'completed', 'cancelled')
      and (r.requested_date + r.requested_time)
        between c.local_now + interval '22 hours' and c.local_now + interval '26 hours'

    union all

    select
      r.id,
      'delivery_2h',
      ('Consegna imminente · ' || r.code),
      (e.name || ' da ' || pickup.short_name || ' a ' || destination.short_name || ' entro le ' || to_char(r.requested_time, 'HH24:MI'))
    from public.delivery_requests r
    join public.equipment e on e.id = r.equipment_id
    join public.sites pickup on pickup.id = r.pickup_site_id
    join public.sites destination on destination.id = r.destination_site_id
    cross join clock c
    where r.status not in ('delivered', 'return_required', 'completed', 'cancelled')
      and (r.requested_date + r.requested_time)
        between c.local_now and c.local_now + interval '2 hours'

    union all

    select
      r.id,
      'overdue',
      ('Consegna in ritardo · ' || r.code),
      (e.name || ' per ' || destination.short_name || ' risulta ancora ' || replace(r.status::text, '_', ' '))
    from public.delivery_requests r
    join public.equipment e on e.id = r.equipment_id
    join public.sites destination on destination.id = r.destination_site_id
    cross join clock c
    where r.status not in ('delivered', 'return_required', 'completed', 'cancelled')
      and (r.requested_date + r.requested_time) < c.local_now
  ), claimed as (
    insert into public.reminder_dispatches (request_id, reminder_key)
    select distinct c.request_id, c.reminder_key
    from candidates c
    on conflict (request_id, reminder_key) do nothing
    returning request_id, reminder_key
  ), inserted as (
    insert into public.app_notifications (kind, title, body, request_id, created_by)
    select 'reminder', c.title, c.body, c.request_id, null
    from candidates c
    join claimed d
      on d.request_id = c.request_id
     and d.reminder_key = c.reminder_key
    returning id
  )
  select inserted.id
  from inserted;
end;
$$;

grant execute on function public.assign_delivery_mover(uuid, uuid) to authenticated;
grant execute on function public.take_delivery_request(uuid, uuid[]) to authenticated;
grant execute on function public.update_delivery_status(uuid, public.request_status) to authenticated;
grant execute on function public.admin_delivery_statistics(date, date, uuid, uuid, uuid, public.request_status, public.request_priority) to authenticated;

commit;

notify pgrst, 'reload schema';

